#!/usr/bin/env ruby

NAME = 'thin'
CONFIG_DIR="/etc/#{NAME}"
ACTIONS = %w(start stop restart)

if ACTIONS.include?(ARGV.first)
  `#{NAME} #{ARGV.first} --all #{CONFIG_DIR}`
else
  puts "Usage /etc/init.d/#{NAME} [#{ACTIONS.join('|')}]"
  exit 1
end